export const VIBES = [
  { key: "village_cultural", label: "Village & Cultural", genres: ["kalindula", "traditional"] },
  { key: "wedding_celebration", label: "Wedding & Celebration", genres: ["kalindula", "afropop", "gospel"] },
  { key: "street_hustle", label: "Street & Hustle", genres: ["zed_hiphop", "dancehall"] },
  { key: "love_relationships", label: "Love & Relationships", genres: ["rnb", "pop", "afropop"] },
  { key: "party_club", label: "Party & Club", genres: ["amapiano", "dancehall", "afrobeat"] },
  { key: "motivation_success", label: "Motivation & Success", genres: ["hiphop", "gospel"] },
  { key: "worship_reflection", label: "Worship & Reflection", genres: ["gospel"] },
  { key: "storytelling_social", label: "Storytelling & Social Issues", genres: ["kalindula", "hiphop", "folk"] },
] as const;

export type VibeKey = (typeof VIBES)[number]["key"];

export const GENRE_LABELS: Record<string, string> = {
  ambient: "Ambient",
  electronic: "Electronic",
  hiphop: "Hip-Hop",
  afrobeats: "Afrobeats",
  classical: "Classical",
  pop: "Pop",
  lofi: "Lo-Fi",
  experimental: "Experimental",
  cinematic: "Cinematic",
  world: "World",
  kalindula: "Kalindula",
  traditional: "Traditional",
  zed_hiphop: "Zed Hip-Hop",
  dancehall: "Dancehall",
  amapiano: "Amapiano",
  afrobeat: "Afrobeat",
  afropop: "Afropop",
  rnb: "R&B",
  gospel: "Gospel",
  folk: "Folk",
  zamrock: "Zamrock",
  kalindula_modern: "Kalindula Modern",
  zed_gospel: "Zed Gospel",
  zed_rnb: "Zed R&B",
  zed_dancehall: "Zed Dancehall",
  kwaito: "Kwaito",
  gqom: "Gqom",
  bongo_flava: "Bongo Flava",
  genge: "Genge",
  gengetone: "Gengetone",
  benga: "Benga",
  taarab: "Taarab",
  soukous: "Soukous",
  rumba: "Rumba",
  ndombolo: "Ndombolo",
  highlife: "Highlife",
  afroswing: "Afroswing",
  afrohouse: "Afro House",
  afrofusion: "Afro Fusion",
  afrosoul: "Afro Soul",
  afro_trap: "Afro Trap",
  naija_pop: "Naija Pop",
  juju: "Jùjú",
  fuji: "Fuji",
  mbalax: "Mbalax",
  coupe_decale: "Coupé-Décalé",
  makossa: "Makossa",
  bikutsi: "Bikutsi",
  chimurenga: "Chimurenga",
  sungura: "Sungura",
  maskandi: "Maskandi",
  mbaqanga: "Mbaqanga",
  shangaan_electro: "Shangaan Electro",
  ethio_jazz: "Ethio-Jazz",
  "raï": "Raï",
  gnawa: "Gnawa",
  mbube: "Mbube",
};

export function prettyGenre(g: string) {
  return GENRE_LABELS[g] ?? g.charAt(0).toUpperCase() + g.slice(1);
}
