/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SafetyPrivacyRouteImport } from './routes/safety-privacy'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FreshInkRouteImport } from './routes/fresh-ink'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as BecomeArtistRouteImport } from './routes/become-artist'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutAdsRouteImport } from './routes/about-ads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TracksIdRouteImport } from './routes/tracks.$id'
import { Route as BecomeArtistSubscribeRouteImport } from './routes/become-artist_.subscribe'
import { Route as ArtistsSlugRouteImport } from './routes/artists.$slug'
import { Route as AlbumsIdRouteImport } from './routes/albums.$id'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyPrivacyRoute = SafetyPrivacyRouteImport.update({
  id: '/safety-privacy',
  path: '/safety-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshInkRoute = FreshInkRouteImport.update({
  id: '/fresh-ink',
  path: '/fresh-ink',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeArtistRoute = BecomeArtistRouteImport.update({
  id: '/become-artist',
  path: '/become-artist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAdsRoute = AboutAdsRouteImport.update({
  id: '/about-ads',
  path: '/about-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TracksIdRoute = TracksIdRouteImport.update({
  id: '/tracks/$id',
  path: '/tracks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeArtistSubscribeRoute = BecomeArtistSubscribeRouteImport.update({
  id: '/become-artist_/subscribe',
  path: '/become-artist/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtistsRoute,
} as any)
const AlbumsIdRoute = AlbumsIdRouteImport.update({
  id: '/albums/$id',
  path: '/albums/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-ads': typeof AboutAdsRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/charts': typeof ChartsRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/fresh-ink': typeof FreshInkRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/radio': typeof RadioRoute
  '/safety-privacy': typeof SafetyPrivacyRoute
  '/upload': typeof UploadRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/become-artist/subscribe': typeof BecomeArtistSubscribeRoute
  '/tracks/$id': typeof TracksIdRoute
  '/admin/': typeof AdminIndexRoute
  '/artists/': typeof ArtistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-ads': typeof AboutAdsRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/charts': typeof ChartsRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/fresh-ink': typeof FreshInkRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/radio': typeof RadioRoute
  '/safety-privacy': typeof SafetyPrivacyRoute
  '/upload': typeof UploadRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/become-artist/subscribe': typeof BecomeArtistSubscribeRoute
  '/tracks/$id': typeof TracksIdRoute
  '/admin': typeof AdminIndexRoute
  '/artists': typeof ArtistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-ads': typeof AboutAdsRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/charts': typeof ChartsRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/fresh-ink': typeof FreshInkRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/privacy': typeof PrivacyRoute
  '/radio': typeof RadioRoute
  '/safety-privacy': typeof SafetyPrivacyRoute
  '/upload': typeof UploadRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/become-artist_/subscribe': typeof BecomeArtistSubscribeRoute
  '/tracks/$id': typeof TracksIdRoute
  '/admin/': typeof AdminIndexRoute
  '/artists/': typeof ArtistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-ads'
    | '/accessibility'
    | '/admin'
    | '/artists'
    | '/auth'
    | '/become-artist'
    | '/charts'
    | '/cookies'
    | '/dashboard'
    | '/discover'
    | '/fresh-ink'
    | '/legal'
    | '/library'
    | '/privacy'
    | '/radio'
    | '/safety-privacy'
    | '/upload'
    | '/admin/subscriptions'
    | '/albums/$id'
    | '/artists/$slug'
    | '/become-artist/subscribe'
    | '/tracks/$id'
    | '/admin/'
    | '/artists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-ads'
    | '/accessibility'
    | '/auth'
    | '/become-artist'
    | '/charts'
    | '/cookies'
    | '/dashboard'
    | '/discover'
    | '/fresh-ink'
    | '/legal'
    | '/library'
    | '/privacy'
    | '/radio'
    | '/safety-privacy'
    | '/upload'
    | '/admin/subscriptions'
    | '/albums/$id'
    | '/artists/$slug'
    | '/become-artist/subscribe'
    | '/tracks/$id'
    | '/admin'
    | '/artists'
  id:
    | '__root__'
    | '/'
    | '/about-ads'
    | '/accessibility'
    | '/admin'
    | '/artists'
    | '/auth'
    | '/become-artist'
    | '/charts'
    | '/cookies'
    | '/dashboard'
    | '/discover'
    | '/fresh-ink'
    | '/legal'
    | '/library'
    | '/privacy'
    | '/radio'
    | '/safety-privacy'
    | '/upload'
    | '/admin/subscriptions'
    | '/albums/$id'
    | '/artists/$slug'
    | '/become-artist_/subscribe'
    | '/tracks/$id'
    | '/admin/'
    | '/artists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutAdsRoute: typeof AboutAdsRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArtistsRoute: typeof ArtistsRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeArtistRoute: typeof BecomeArtistRoute
  ChartsRoute: typeof ChartsRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  FreshInkRoute: typeof FreshInkRoute
  LegalRoute: typeof LegalRoute
  LibraryRoute: typeof LibraryRoute
  PrivacyRoute: typeof PrivacyRoute
  RadioRoute: typeof RadioRoute
  SafetyPrivacyRoute: typeof SafetyPrivacyRoute
  UploadRoute: typeof UploadRoute
  AlbumsIdRoute: typeof AlbumsIdRoute
  BecomeArtistSubscribeRoute: typeof BecomeArtistSubscribeRoute
  TracksIdRoute: typeof TracksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-privacy': {
      id: '/safety-privacy'
      path: '/safety-privacy'
      fullPath: '/safety-privacy'
      preLoaderRoute: typeof SafetyPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fresh-ink': {
      id: '/fresh-ink'
      path: '/fresh-ink'
      fullPath: '/fresh-ink'
      preLoaderRoute: typeof FreshInkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-artist': {
      id: '/become-artist'
      path: '/become-artist'
      fullPath: '/become-artist'
      preLoaderRoute: typeof BecomeArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-ads': {
      id: '/about-ads'
      path: '/about-ads'
      fullPath: '/about-ads'
      preLoaderRoute: typeof AboutAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tracks/$id': {
      id: '/tracks/$id'
      path: '/tracks/$id'
      fullPath: '/tracks/$id'
      preLoaderRoute: typeof TracksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-artist_/subscribe': {
      id: '/become-artist_/subscribe'
      path: '/become-artist/subscribe'
      fullPath: '/become-artist/subscribe'
      preLoaderRoute: typeof BecomeArtistSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/albums/$id': {
      id: '/albums/$id'
      path: '/albums/$id'
      fullPath: '/albums/$id'
      preLoaderRoute: typeof AlbumsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArtistsRouteChildren {
  ArtistsSlugRoute: typeof ArtistsSlugRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsSlugRoute: ArtistsSlugRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutAdsRoute: AboutAdsRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRouteWithChildren,
  ArtistsRoute: ArtistsRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeArtistRoute: BecomeArtistRoute,
  ChartsRoute: ChartsRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  FreshInkRoute: FreshInkRoute,
  LegalRoute: LegalRoute,
  LibraryRoute: LibraryRoute,
  PrivacyRoute: PrivacyRoute,
  RadioRoute: RadioRoute,
  SafetyPrivacyRoute: SafetyPrivacyRoute,
  UploadRoute: UploadRoute,
  AlbumsIdRoute: AlbumsIdRoute,
  BecomeArtistSubscribeRoute: BecomeArtistSubscribeRoute,
  TracksIdRoute: TracksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
