/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FreshInkRouteImport } from './routes/fresh-ink'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as BecomeArtistRouteImport } from './routes/become-artist'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TracksIdRouteImport } from './routes/tracks.$id'
import { Route as BecomeArtistSubscribeRouteImport } from './routes/become-artist_.subscribe'
import { Route as ArtistsSlugRouteImport } from './routes/artists.$slug'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshInkRoute = FreshInkRouteImport.update({
  id: '/fresh-ink',
  path: '/fresh-ink',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeArtistRoute = BecomeArtistRouteImport.update({
  id: '/become-artist',
  path: '/become-artist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TracksIdRoute = TracksIdRouteImport.update({
  id: '/tracks/$id',
  path: '/tracks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeArtistSubscribeRoute = BecomeArtistSubscribeRouteImport.update({
  id: '/become-artist_/subscribe',
  path: '/become-artist/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtistsRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/charts': typeof ChartsRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/fresh-ink': typeof FreshInkRoute
  '/library': typeof LibraryRoute
  '/radio': typeof RadioRoute
  '/upload': typeof UploadRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/become-artist/subscribe': typeof BecomeArtistSubscribeRoute
  '/tracks/$id': typeof TracksIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/charts': typeof ChartsRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/fresh-ink': typeof FreshInkRoute
  '/library': typeof LibraryRoute
  '/radio': typeof RadioRoute
  '/upload': typeof UploadRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/become-artist/subscribe': typeof BecomeArtistSubscribeRoute
  '/tracks/$id': typeof TracksIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-artist': typeof BecomeArtistRoute
  '/charts': typeof ChartsRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/fresh-ink': typeof FreshInkRoute
  '/library': typeof LibraryRoute
  '/radio': typeof RadioRoute
  '/upload': typeof UploadRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/become-artist_/subscribe': typeof BecomeArtistSubscribeRoute
  '/tracks/$id': typeof TracksIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/artists'
    | '/auth'
    | '/become-artist'
    | '/charts'
    | '/dashboard'
    | '/discover'
    | '/fresh-ink'
    | '/library'
    | '/radio'
    | '/upload'
    | '/admin/subscriptions'
    | '/artists/$slug'
    | '/become-artist/subscribe'
    | '/tracks/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artists'
    | '/auth'
    | '/become-artist'
    | '/charts'
    | '/dashboard'
    | '/discover'
    | '/fresh-ink'
    | '/library'
    | '/radio'
    | '/upload'
    | '/admin/subscriptions'
    | '/artists/$slug'
    | '/become-artist/subscribe'
    | '/tracks/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/artists'
    | '/auth'
    | '/become-artist'
    | '/charts'
    | '/dashboard'
    | '/discover'
    | '/fresh-ink'
    | '/library'
    | '/radio'
    | '/upload'
    | '/admin/subscriptions'
    | '/artists/$slug'
    | '/become-artist_/subscribe'
    | '/tracks/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArtistsRoute: typeof ArtistsRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeArtistRoute: typeof BecomeArtistRoute
  ChartsRoute: typeof ChartsRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  FreshInkRoute: typeof FreshInkRoute
  LibraryRoute: typeof LibraryRoute
  RadioRoute: typeof RadioRoute
  UploadRoute: typeof UploadRoute
  BecomeArtistSubscribeRoute: typeof BecomeArtistSubscribeRoute
  TracksIdRoute: typeof TracksIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fresh-ink': {
      id: '/fresh-ink'
      path: '/fresh-ink'
      fullPath: '/fresh-ink'
      preLoaderRoute: typeof FreshInkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-artist': {
      id: '/become-artist'
      path: '/become-artist'
      fullPath: '/become-artist'
      preLoaderRoute: typeof BecomeArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tracks/$id': {
      id: '/tracks/$id'
      path: '/tracks/$id'
      fullPath: '/tracks/$id'
      preLoaderRoute: typeof TracksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-artist_/subscribe': {
      id: '/become-artist_/subscribe'
      path: '/become-artist/subscribe'
      fullPath: '/become-artist/subscribe'
      preLoaderRoute: typeof BecomeArtistSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArtistsRouteChildren {
  ArtistsSlugRoute: typeof ArtistsSlugRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsSlugRoute: ArtistsSlugRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArtistsRoute: ArtistsRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeArtistRoute: BecomeArtistRoute,
  ChartsRoute: ChartsRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  FreshInkRoute: FreshInkRoute,
  LibraryRoute: LibraryRoute,
  RadioRoute: RadioRoute,
  UploadRoute: UploadRoute,
  BecomeArtistSubscribeRoute: BecomeArtistSubscribeRoute,
  TracksIdRoute: TracksIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
